name: rSapka
author: Green
version: 1.0.1
description: Texturepackli sunucular için şapka plugini
main: com.minewebtr.rsapka.RSapka
api-version: 1.16
depend: [SmartInvs,Vault,CMI]
commands:
  rsapka:
    aliases:
      - sapka
      - şapka
    description: Şapka Menüsünü Açar
