name: rSapka
author: FurkanZhlp
version: 1.0.1
description: 1.16.5 Helmet Plugin
main: git.furkanzhlp.helmet.Texturehelmets
api-version: 1.16
depend: [SmartInvs,Vault]
commands:
  helmet:
    aliases:
      - helmets
    description: Open's helmet menu
